name:                PDP11
version:             0.1.0.0
github:              "githubuser/PDP11"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/PDP11#readme>

dependencies:
- base >= 4.7 && < 5
- array
- lens
- mtl
- parsec >= 3.1

library:
  source-dirs: src

executables:
  PDP11-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - PDP11
  PDP11-bot:
    source-dirs:         discord
    main:                PDP11-bot.hs
    dependencies:
      - PDP11
      - base==4.*
      - discord-hs
      - text==1.2.*
      - array
      - lens
      - parsec >=3.1
      - req

tests:
  PDP11-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PDP11
    - hspec
